package com.kalex.expenses.data.db

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a financial or contractual obligation.
 *
 * This data class models an obligation with its relevant details,
 * such as name, description, amount, due date, status, type, and whether
 * it's set up for automatic payment.
 *
 * @property id The unique identifier for the obligation. This is auto-generated by the database.
 * @property name The name of the obligation (e.g., "Rent", "Credit Card Payment").
 * @property description A detailed description of the obligation.
 * @property amount The monetary amount of the obligation.
 * @property date The due date or payment date of the obligation, represented as a String.
 *                          (Consider using a Date/Time object for better date management).
 * @property status The current status of the obligation (e.g., "Pending", "Paid", "Overdue").
 * @property type The type of obligation (e.g., "Bill", "Loan", "Subscription").
 * @property automaticPayment Indicates whether the obligation is set up for automatic payment.
 *
 * @author Kevin Alexander Soto on 3/9/2025
 */
@Entity
data class Obligation(

    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "obligation_id")
    val id: Int,

    @ColumnInfo(name = "obligation_name")
    val name: String,

    @ColumnInfo(name = "obligation_description")
    val description: String,

    @ColumnInfo(name = "obligation_amount")
    val amount: Double,

    @ColumnInfo(name = "obligation_date")
    val date: String,

    @ColumnInfo(name = "obligation_status")
    val status: String,

    @ColumnInfo(name = "obligation_type")
    val type: String,

    @ColumnInfo(name = "obligation_automatic_payment")
    val automaticPayment: Boolean,

    )
